owner: HaffMedia
repo: Swiptly-Sites

sites:
  - name: Swiptly
    url: https://swiptly.io
  - name: Scribe Associates
    url: https://scribeassociatesltd.co.uk
  - name: GMLPF
    url: https://gmlpf.net
  - name: GMLPF
    url: https://gmlpf.net
  - name: Mode
    url: https://modetraining.co.uk
  - name: The Child Care Academy
    url: https://thechildcareacademy.co.uk
  - name: Its Fresh
    url: https://itsfresh.com
  - name: Towers Associates
    url: https://towersassociates.co.uk
  - name: Vitality Maestros
    url: https://vitalitymaestros.com
  - name: We are the Property Maestros
    url: https://wearethepropertymaestros.com
  - name: Grace Jukes
    url: https://gracejukes.com
  - name: Team Jukes
    url: https://teamjukes.com
  - name: Go Local EPC
    url: https://golocalepc.co.uk
  - name: TRS Training
    url: https://trstrainingltd.com
  - name: Maxxia
    url: https://maxxia.co.uk
  - name: Van Driver Toolkit
    url: https://vandrivertoolkit.co.uk
  - name: Driving for Better Business
    url: https://drivingforbetterbusiness.com
  - name: Leisure Property Forum
    url: https://leisurepropertyforum.co.uk
  - name: Saucy Horse
    url: https://saucyhorse.co.uk
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /Swiptly-Sites
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Swiptly Managed Site Monitoring
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
